### ISSUE TITLE
Installation stuck at executeStepCopyTemplate

### ISSUE THREAD

**Issue by sandra-arato** [iamturns/create-exposed-app#108]
# :bug: Bug report

As I go through the getting started, and run the `npm init exposed-app`, my terminal gets stuck after the new 'hello-world' git branch is checked out.

## Steps to reproduce

1. Install create-exposed-app on a Windows 7 machine 
2. Run npm init exposed-app

Please include if possible and/or relevant: code, config, links, repository that reproduces the bug.

## Expected behavior

Installation should progress to 'Copying 50 files' as per the gif shows on the Read me.

## Actual behaviour

No error message is logged, and the Terminal session keeps hangin.

## Environment

- `create-exposed-app` version: latest
- Node.js version: v10.13.0
- npm version: 6.4.1
- Operating System and version: Windows 7 
- Device used: N/A
- Browser name and version: N/A

## Additional

No ideas.

---

:white_check_mark: Checklist

- [X] Following [CODE_OF_CONDUCT.md](https://github.com/iamturns/create-exposed-app/blob/master/CODE_OF_CONDUCT.md)
- [X] Checked for [duplicate bug reports](https://github.com/iamturns/create-exposed-app/issues?q=label%3Abug)
- [X] Title is a summary of the bug report, in present tense, and ideally < 50 characters
- [x] Ready for review

**Comment by iamturns** [comment]
Hey @sandra-arato 

Sorry about the bug. Unfortunately I don't have a Windows 7 OS to test this on.

Could you please run the command with an environment variable of `DEBUG` set to `create-exposed-app`. And paste last parts of the output (where it attempts to copy the template files).

Hopefully it points to a solution 🤞 

Thanks!

**Comment by sandra-arato** [comment]
thanks @iamturns  -- will do so. Will let you know if there's a fix, otherwise please feel free to close this bug as unresolved.

**Comment by sandra-arato** [comment]
hey @iamturns - couldn't find a resolution, and stepped back to create-react-app with typescript. happy to close this one if you are too. thanks :)
