### ISSUE TITLE
markdownlint found some errors. Please fix them and try committing again.

### ISSUE THREAD

**Issue by dewijones92** [iamturns/create-exposed-app#116]
# :bug: Bug report

On commit 87556848c62fa8e8fea1820fd4d75c14742fc4d6
I run create-exposed-app-cli.js
I try add all those files to git and commit - git commit -m "Add files"
error mesage:
`     ✖ markdownlint
      Running tasks for **/*.{css,gql,graphql,html,json,less,md,mdx,scss,vue,yaml,yml}
      Running tasks for **/*.{js,jsx,ts,tsx}
      Running tasks for src/**/*

✖ markdownlint found some errors. Please fix them and try committing again.

/home/dewi/tempdewi/test6/docs/adr/README.md: 5: MD041/first-line-h1 First line in file should be a top level heading [Context: "- [ADRs](#adrs)"]`

**Comment by iamturns** [comment]
This repository has just had a complete rewrite. Closing all existing issues. Please report again if the issue persists. Thanks!
